clickhouse:
  host: "localhost"
  port: 9000
  user: "default"
  password: ""
  database: "default"
  table: "logs"
  format: "JSONEachRow"
  batch_size: 1000
  batch_interval: 1
  batch_interval_unit: "second"
  batch_interval_unit_type: "strptime"
  batch_interval_unit_timezone: "UTC"
  batch_interval_unit_dst: false
  batch_interval_unit_dst_offset: 0
  batch_interval_unit_dst_start: "02:00:00"
  batch_interval_unit_dst_end: "03:00:00"
  batch_interval_unit_format: "%Y-%m-%d %H:%M:%S"
