#system configuration
system:
  print_enabled: true # 是否打印配置信息
  use_elk : true # 是否使用elk
  read_path: ["/Users/yelei/data/code/go-projects/logs"] # watch监控目录列表
  max_read_count: 100 # 监控到文件变化时，读取文件最大次数
  state_file_path: "/state/core.json" # 记录监控文件的offset
  root_path: "" # app系统根目录
  consumer_log_channel_size: 1000
  consumer_batch_interval: 5 # 秒， 批量日志检查缓存列表时间间隔
  consumer_batch_size: 100 # 批量日志单次批量提交最大值
  consumer_batch_capacity: 100 # 批量日志缓存容量
  consumer_batch_auto_flush: true # 批量日志是否自动刷新


