# watch监控目录列表
watch :
  read_path : # read_path每个Key的目录不可以重复，且value不可以包含相同的子集
    index_nginx: ["/Users/yelei/data/code/go-projects/logs/nginx"] # 必须是目录
    index_admin : [ "/Users/yelei/data/code/go-projects/logs/admin"]
    index_api : [ "/Users/yelei/data/code/go-projects/logs/api"]
  max_read_count : 100 # 监控到文件变化时，一次读取文件最大次数
  start_date : "2020-01-01 00:00:00" # 监控什么时间起创建的文件
  obsolete_date_interval : 1 # 单位小时hour, 默认1小时, 超过多少时间文件未变化, 认为文件应该删除
  state_file_path : "/state/core.json" # 记录监控文件的offset